### ISSUE TITLE
Create the templates/layouts for blog posts

### ISSUE THREAD

**Issue by audiodude** [CuriosityHacked/curiosityhacked.org#10]
The layouts are the basic wrapper around the blog index and the individual blog posts, aka how they will show up on the site. This is going to manifest as a couple of files in _layouts, like _layouts/blog_index.html and maybe _layouts/post.html respectively. Depending on what the desired UI is, this will probably be similar to default.html, except that they might not include the sidebar in the content but instead put the sidebar in the template so it can show an index/list of posts.

**Comment by chriscook8** [comment]
First pass
dd48b20a69caa2337b7aee01fc9f45354d54394c

ok.. jekyll is cool. I see how this will play out using subdirs as categories and tags to denote promotion to front page. 
Unfortunatly pagination doesn't support either so I might fake it with the javascript in blog/index

**Comment by chriscook8** [comment]
/blogs links to all the available category blogs and then there is an index for each. base line templates are all in place and most of the blogs have migrated from the old system smoothly.. there is still a bit of manual formating cleanup to be done with old blog entries

**Comment by audiodude** [comment]
This is great work! It seems very simple now, but definitely something that can be incrementally improved.
