### ISSUE TITLE
Update README.md to include information on how to create a new blog for a guild

### ISSUE THREAD

**Issue by audiodude** [CuriosityHacked/curiosityhacked.org#11]
Once #10 is fixed, we can start adding blogs to the site. We should update the README.md file to include a section on the process for this. Basically, the process includes:
- Create a sub-directory, either at the top level, or under a new blogs/ directory, for the guild that will be blogging. This is likely to be copied from a `_blog_template/` directory (that doesn't exist yet).
- Edit the index page to be specific to the guild.
- Train those who will be writing blog posts in the use of Prose.io. It is possible that the README could contain instructional steps with screenshots.

**Comment by chriscook8** [comment]
Wrote dedicated wiki on these topics.. cleaner to point new users to:
https://github.com/CuriosityHacked/curiosityhacked.org/wiki/How-to-Blog
