### ISSUE TITLE
No feedback to user when sign up form fails to submit

### ISSUE THREAD

**Issue by funrollloops** [CuriosityHacked/curiosityhacked.org#6]
I know I suggested we do this, but I've been bitten by this twice now while testing.

Maybe we should drop the Ajax and set the action on the form appropriately? It's not the end of the world if we reveal we're using Google Forms.

**Comment by audiodude** [comment]
I agree, proper feedback is more important than hiding the fact that we're using Google Forms

This is the result I get:

![screen shot 2014-08-03 at 11 54 31](https://cloud.githubusercontent.com/assets/57832/3791474/a1530746-1b3f-11e4-83cd-7c89babb01a9.png)

**Comment by audiodude** [comment]
I've created the above PR to fix this, if everyone thinks it's good to go you can auto merge it.

**Comment by chriscook8** [comment]
So this leaves them on the Google Forms 'Thank you for your interest' page?  Maybe we change the confirmation page text to "Thank you for your interest! Return to http://www.curiosityhacked.org" or something so it's not a navigational dead end. But then again if they have given us their contact info then we could consider it already a win.

**Comment by audiodude** [comment]
We control that message, and URLs are autolinked. How's this?

Feel free to merge the Pull Request if this looks fine.

![screen shot 2014-08-03 at 16 57 32](https://cloud.githubusercontent.com/assets/57832/3792185/011a7220-1b6a-11e4-8d7c-1ecb3f412a94.png)
