### ISSUE TITLE
Maintenance: delete master branch, it is not needed

### ISSUE THREAD

**Issue by audiodude** [CuriosityHacked/curiosityhacked.org#8]
Since this is not a normal github repo, but instead exists only to host the curiosityhacked.org website, there is no need for the repo to have a 'master' branch. It is only confusing to people viewing the repo, and should be removed.

**Comment by audiodude** [comment]
@chriscook8, you need to go to the project settings and set gh-pages as the default branch. Otherwise I get this in the console:

```
$ git push origin --delete master
remote: error: refusing to delete the current branch: refs/heads/master
To git@github.com:CuriosityHacked/curiosityhacked.org.git
 ! [remote rejected] master (deletion of the current branch prohibited)
error: failed to push some refs to 'git@github.com:CuriosityHacked/curiosityhacked.org.git'
```

**Comment by chriscook8** [comment]
Hey look I'm githubbing!

default moved and master branch removed

**Comment by audiodude** [comment]
Nice! :+1:
